"""Added initial table

Revision ID: 106647177983
Revises: 
Create Date: 2024-07-19 08:00:58.984676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.model


# revision identifiers, used by Alembic.
revision: str = '106647177983'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('surah',
    sa.Column('arabic', sa.String(), nullable=True),
    sa.Column('latin', sa.String(), nullable=True),
    sa.Column('number_of_verse', sa.Integer(), nullable=True),
    sa.Column('id_translation', sa.String(), nullable=True),
    sa.Column('en_translation', sa.String(), nullable=True),
    sa.Column('revelation_type', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_surah_arabic'), 'surah', ['arabic'], unique=False)
    op.create_index(op.f('ix_surah_en_translation'), 'surah', ['en_translation'], unique=False)
    op.create_index(op.f('ix_surah_id'), 'surah', ['id'], unique=False)
    op.create_index(op.f('ix_surah_id_translation'), 'surah', ['id_translation'], unique=False)
    op.create_index(op.f('ix_surah_latin'), 'surah', ['latin'], unique=False)
    op.create_table('topic',
    sa.Column('en_title', sa.String(), nullable=True),
    sa.Column('id_title', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topic_en_title'), 'topic', ['en_title'], unique=False)
    op.create_index(op.f('ix_topic_id'), 'topic', ['id'], unique=False)
    op.create_index(op.f('ix_topic_id_title'), 'topic', ['id_title'], unique=False)
    op.create_table('verse',
    sa.Column('surah_id', sa.Integer(), nullable=True),
    sa.Column('verse_number', sa.Integer(), nullable=True),
    sa.Column('juz', sa.Integer(), nullable=True),
    sa.Column('arabic', sa.String(), nullable=True),
    sa.Column('latin', sa.String(), nullable=True),
    sa.Column('id_translation', sa.String(), nullable=True),
    sa.Column('en_translation', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['surah_id'], ['surah.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verse_arabic'), 'verse', ['arabic'], unique=False)
    op.create_index(op.f('ix_verse_en_translation'), 'verse', ['en_translation'], unique=False)
    op.create_index(op.f('ix_verse_id'), 'verse', ['id'], unique=False)
    op.create_index(op.f('ix_verse_id_translation'), 'verse', ['id_translation'], unique=False)
    op.create_index(op.f('ix_verse_latin'), 'verse', ['latin'], unique=False)
    op.create_table('verse_topic',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('verse_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['verse_id'], ['verse.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verse_topic')
    op.drop_index(op.f('ix_verse_latin'), table_name='verse')
    op.drop_index(op.f('ix_verse_id_translation'), table_name='verse')
    op.drop_index(op.f('ix_verse_id'), table_name='verse')
    op.drop_index(op.f('ix_verse_en_translation'), table_name='verse')
    op.drop_index(op.f('ix_verse_arabic'), table_name='verse')
    op.drop_table('verse')
    op.drop_index(op.f('ix_topic_id_title'), table_name='topic')
    op.drop_index(op.f('ix_topic_id'), table_name='topic')
    op.drop_index(op.f('ix_topic_en_title'), table_name='topic')
    op.drop_table('topic')
    op.drop_index(op.f('ix_surah_latin'), table_name='surah')
    op.drop_index(op.f('ix_surah_id_translation'), table_name='surah')
    op.drop_index(op.f('ix_surah_id'), table_name='surah')
    op.drop_index(op.f('ix_surah_en_translation'), table_name='surah')
    op.drop_index(op.f('ix_surah_arabic'), table_name='surah')
    op.drop_table('surah')
    # ### end Alembic commands ###
